
@host=http://localhost:8000
@username=newuser
@email=new@user.com
@password=new_user_password
@token=dcb445c2ea246d5d414277e1cdd9ca56b5d8cfb3

### Create New Account

POST {{host}}/auth/users/
Content-type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "re_password": "{{password}}"
}


### Login

POST {{host}}/auth/token/login/
Content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


### logout
POST {{host}}/auth/token/logout/
Authorization: token {{token}}
